sudo: required

services:
  - docker

before_install:
  - id

install:
  - docker-compose up -d mysql
  - docker-compose build php
  - docker-compose -f docker-compose.yml -f docker-compose-tools.yml run -u $(id -u) --rm composer validate --no-cache
  - docker-compose -f docker-compose.yml -f docker-compose-tools.yml run -u $(id -u) --rm composer
  - mkdir -p tests/coverage && chmod 0777 tests/coverage
  - until docker-compose exec -T mysql mysql -uroot -proot -e "select now()"; do echo "waiting..."; sleep 1; done
  
script:
  - docker-compose -f docker-compose.yml -f docker-compose-tools.yml run -u $(id -u) --rm phpcsfixer
  - docker-compose -f docker-compose.yml -f docker-compose-tools.yml run -u $(id -u) --rm psalm
  - docker-compose -f docker-compose.yml -f docker-compose-tools.yml run -u $(id -u) --rm shell update_database.php
  - docker-compose -f docker-compose.yml -f docker-compose-tools.yml run -u $(id -u) --rm phpunit
  - docker-compose -f docker-compose.yml -f docker-compose-tools.yml run -u $(id -u) --rm phploc
