version: "2.1"

services:
  shell:
    image: example_tasks_php
    cap_drop: [all]
    working_dir: /var/www/src/shell
    entrypoint: php
    volumes:
      - ./tasks/:/var/www
    networks:
      - backend
    links:
      - mysql
  composer:
    image: example_tasks_php
    cap_drop: [all]
    working_dir: /var/www
    entrypoint: composer-209.phar
    command: install --no-dev --no-cache --no-progress -o -a --ignore-platform-reqs
    volumes:
      - ./tasks/:/var/www
      - ./bin:/usr/local/sbin
  composer_dev:
    image: example_tasks_php
    cap_drop: [all]
    working_dir: /var/www
    entrypoint: composer-209.phar
    command: install --no-cache --no-progress -o --ignore-platform-reqs
    volumes:
      - ./tasks/:/var/www
      - ./bin:/usr/local/sbin
  composer_validate:
    image: example_tasks_php
    cap_drop: [all]
    working_dir: /var/www
    entrypoint: composer-209.phar
    command: validate --no-cache
    volumes:
      - ./tasks/:/var/www
      - ./bin:/usr/local/sbin
  fpm_status:
    image: example_tasks_php
    cap_drop: [all]
    working_dir: /var/www
    entrypoint: php src/shell/fpm_status.php
    volumes:
      - ./tasks/:/var/www
    networks:
      - backend
    links:
      - php
  psalm:
    image: example_tasks_php
    cap_drop: [all]
    working_dir: /var/www
    entrypoint: psalm-464.phar --no-cache
    volumes:
      - ./tasks/:/var/www
      - ./bin:/usr/local/sbin
  psalm_taint:
    image: example_tasks_php
    cap_drop: [all]
    working_dir: /var/www
    entrypoint: psalm-464.phar --no-cache --taint-analysis
    volumes:
      - ./tasks/:/var/www
      - ./bin:/usr/local/sbin
  phpcsfixer:
    image: example_tasks_php
    cap_drop: [all]
    working_dir: /var/www
    entrypoint: phpcsfixer-2182.phar fix --verbose --dry-run --diff --config phpcsfixer.conf
    volumes:
      - ./tasks/:/var/www
      - ./bin:/usr/local/sbin
  phpunit:
    image: example_tasks_php
    cap_drop: [all]
    working_dir: /var/www
    entrypoint: php -dmemory_limit=64M -dextension=pcov.so /usr/local/sbin/phpunit-952.phar --testdox --coverage-text --coverage-html=/var/coverage
    volumes:
      - coverage-data:/var/coverage
      - ./tasks/:/var/www
      - ./bin:/usr/local/sbin
    networks:
      - backend
    links:
      - nginx
      - php
      - mysql
      - mailhog
  phploc:
    image: example_tasks_php
    cap_drop: [all]
    working_dir: /var/www
    entrypoint: php -dmemory_limit=128M /usr/local/sbin/phploc-702.phar ./
    volumes:
      - ./tasks/:/var/www
      - ./bin:/usr/local/sbin
  apib2swagger:
    image: kminami/apib2swagger
    cap_drop: [all]
    working_dir: /docs
    command: -i api.md --prefer-reference --bearer-apikey -o swaggerui/api_spec.json
    volumes:
      - ./docs:/docs

networks:
  backend:
    driver: bridge
