name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: check env
      run: docker version && docker-compose version && docker images && cat /proc/cpuinfo && free

    - name: Build containers
      run: docker-compose -f docker-compose.yml -f docker-compose-tasks.yml build --parallel

    - name: Show local docker images
      run: docker images

    - name: Trivy vulnerability scanner in repo mode
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: fs
        exit-code: 1
        scan-ref: ./

    - name: Trivy vulnerability scanner php
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: example_tasks_php:latest
        exit-code: 1

    - name: Trivy vulnerability scanner mysql
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: example_tasks_mysql:latest
        ignore-unfixed: true
        exit-code: 1

    - name: Trivy vulnerability scanner nginx
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: example_tasks_nginx:latest
        exit-code: 1

    - name: Trivy vulnerability scanner mailhog
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: example_tasks_mailhog:latest
        exit-code: 1

    - name: Trivy vulnerability scanner logger
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: example_tasks_logger:latest
        exit-code: 1

    - name: Trivy vulnerability scanner apib2swagger
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: example_tasks_apib2swagger
        exit-code: 1

    - name: Trivy vulnerability scanner apib2html
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: example_tasks_apib2html
        exit-code: 1

    - name: Trivy vulnerability scanner redis
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: redis:6.2-alpine
        exit-code: 1

    - name: local PHP security checker
      run: find ./ -name "composer.lock" -not -path "*/vendor/*" | xargs -ti bin/localphpsecuritychecker-120 --path={}

    - name: Start mysql container
      run: docker-compose up -d mysql redis

    - name: Validate composer file
      run: docker-compose -f docker-compose.yml -f docker-compose-tasks.yml run -u $(id -u) --rm composer_validate

    - name: Run composer
      run: docker-compose -f docker-compose.yml -f docker-compose-tasks.yml run -u $(id -u) --rm composer

    - name: Create coverage directory
      run: mkdir -p tests/coverage && chmod 0777 tests/coverage

    - name: Run phpcsfixer
      run: docker-compose -f docker-compose.yml -f docker-compose-tasks.yml run -u $(id -u) --rm phpcsfixer
      
    - name: Run psalm
      run: docker-compose -f docker-compose.yml -f docker-compose-tasks.yml run -u $(id -u) --rm psalm

    - name: Run psalm taint analysis
      run: docker-compose -f docker-compose.yml -f docker-compose-tasks.yml run -u $(id -u) --rm psalm_taint

    - name: Run phpstan
      run: docker-compose -f docker-compose.yml -f docker-compose-tasks.yml run -u $(id -u) --rm phpstan

    - name: Wait for database to be ready
      run: until docker-compose exec -T mysql mysql -uroot -proot -e "select now()"; do echo "waiting..."; sleep 1; done

    - name: Run update datebase
      run: docker-compose -f docker-compose.yml -f docker-compose-tasks.yml run -u $(id -u) --rm shell update_database.php

    - name: Run phpunit
      run: docker-compose -f docker-compose.yml -f docker-compose-tasks.yml run -u $(id -u) --rm phpunit

    - name: Run phploc
      run: docker-compose -f docker-compose.yml -f docker-compose-tasks.yml run -u $(id -u) --rm phploc
