name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Start mysql container
      run: docker-compose up -d mysql

    - name: Build php container
      run: docker-compose build php

    - name: Validate composer file
      run: docker-compose -f docker-compose.yml -f docker-compose-tools.yml run -u $(id -u) --rm composer validate --no-cache

    - name: Run composer
      run: docker-compose -f docker-compose.yml -f docker-compose-tools.yml run -u $(id -u) --rm composer

    - name: Create coverage directory
      run: mkdir -p tests/coverage && chmod 0777 tests/coverage

    - name: Wait for database to be ready  
      run: until docker-compose exec -T mysql mysql -uroot -proot -e "select now()"; do echo "waiting..."; sleep 1; done

    - name: Run phpcsfixer
      run: docker-compose -f docker-compose.yml -f docker-compose-tools.yml run -u $(id -u) --rm phpcsfixer
      
    - name: Run psalm
      run: docker-compose -f docker-compose.yml -f docker-compose-tools.yml run -u $(id -u) --rm psalm

    - name: Run psalm taint analysis
      run: docker-compose -f docker-compose.yml -f docker-compose-tools.yml run -u $(id -u) --rm psalm_taint

    - name: Run update datebase
      run: docker-compose -f docker-compose.yml -f docker-compose-tools.yml run -u $(id -u) --rm shell update_database.php

    - name: Run phpunit
      run: docker-compose -f docker-compose.yml -f docker-compose-tools.yml run -u $(id -u) --rm phpunit

    - name: Run phploc
      run: docker-compose -f docker-compose.yml -f docker-compose-tools.yml run -u $(id -u) --rm phploc
